language: python

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - HYPOTHESIS_PROFILE=ci

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=py37
    - python: 2.7
      env: TOXENV=pep8
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=py3pep8
    - python: 3.7
      dist: xenial
      sudo: required
      env: TOXENV=docs

install:
  - pip install virtualenv wheel
  - pip install -U pip
  - python -m virtualenv ~/.venv
  - source ~/.venv/bin/activate
  - pip install tox codecov


script:
  - source ~/.venv/bin/activate
  - tox

after_success:
  - ./.travis/upload_coverage.sh

after_script:
  - cat .tox/$TOXENV/log/$TOXENV-*.log
